name: Publish Docker image1

on:
      push:
        branches:
          - 'master'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push worker image
        uses: docker/build-push-action@v4
        with:
          context: worker
          push: true
          tags: fuad1993/docker-hub-test:latest

      - name: Build and push client image
        uses: docker/build-push-action@v4
        with:
          context: client
          push: true
          tags: fuad1993/docker-hub-test:latest

      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: server
          push: true
          tags: fuad1993/docker-hub-test:latest

      - name: Build and push nginx image
        uses: docker/build-push-action@v4
        with:
          context: nginx
          push: true
          tags: fuad1993/docker-hub-test:latest
